version: 2

updates:
- package-ecosystem: "npm"
  directory: "/airflow/www"
  registries: "*"
  schedule:
    interval: "weekly"
  cooldown:
    default-days: 7
  groups:
    npm-dependencies:
      patterns:
        - '*'

- package-ecosystem: "pip"
  directories: 
  - "/"
  - "/airflow/providers/cncf/kubernetes"
  - "/airflow/providers/google"
  - "/airflow/providers/slack"
  - "/airflow/providers/oracle"
  - "/airflow/providers/apache/kafka"
  - "/airflow/providers/smtp" 
  - "/airflow/providers/ssh"
  - "/airflow/providers/sftp"
  - "/airflow/providers/snowflake"
  schedule:
    interval: "weekly"
  groups:
    pip:
      patterns:
        - "*"
