version: 2

updates:
- package-ecosystem: "npm"
  directory: "/airflow/www"
  registries: "*"
  schedule:
    interval: "weekly"
  cooldown:
    default-days: 7
  groups:
    npm-dependencies:
      patterns:
        - '*'

- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    pip:
      patterns:
        - "*"
